# Dependency review configuration

# Specify which package ecosystems to review
package-ecosystems:
  - npm
  - github-actions

# Specify severity levels to block
fail-on-severity:
  - critical
  - high

# Ignore specific vulnerabilities
allow-dependencies:
  - dependency-name: "node"
    versions: ["18.x"]
  
  # Temporary allowances for known but non-critical issues
  - dependency-name: "next"
    reason: "Pending comprehensive review"

# Custom warning thresholds
warn-on-severity:
  - moderate

# Additional configuration options
allow-ghactions-access: true
require-review-for-all-dependencies: true
