name: Repository Protection Rules

# Branch Protection for Main Branch
rules:
  - name: Main Branch Protection
    branches: 
      - main
    protection:
      # Require pull request reviews
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: false

      # Require status checks
      required_status_checks:
        strict: true
        contexts:
          - lint
          - test
          - build
          - security-scan

      # Enforce linear history
      required_linear_history: true

      # Restrict force pushes
      allow_force_pushes: false

      # Restrict branch deletions
      allow_deletions: false

  # Additional branch protections for feature branches
  - name: Feature Branch Rules
    branches: 
      - 'feature/*'
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1

# Repository-wide rules
repository_rules:
  # Require signed commits
  require_signed_commits: true

  # Restrict push access
  push_restrictions:
    - maintainers
    - collaborators

# Security and compliance
security:
  # Require up-to-date dependencies
  dependabot_alerts: true
  
  # Require security vulnerability scanning
  code_scanning_alerts: true

# Workflow triggers
workflow_triggers:
  # Auto-merge for minor updates
  auto_merge:
    - match: 'dependabot/**'
      strategy: squash
