name: 'Dependency Review'
on: [pull_request]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3

      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
        with:
          # Fail the build if there are dependency changes with high/critical vulnerabilities
          fail-on-severity: high
          
          # Optional: Specify additional configuration
          config-file: '.github/dependency-review-config.yml'
