name: Security Scanning

on:
  # Scan weekly
  schedule:
    - cron: '0 0 * * 0'  # Every Sunday at midnight
  
  # Manual trigger
  workflow_dispatch:

# Permissions needed for CodeQL and security scans
permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  # GitHub CodeQL Analysis
  analyze:
    name: CodeQL Security Analysis
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    # Initialize CodeQL
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: javascript, typescript
    
    # Perform analysis
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
  
  # Dependency vulnerability check
  dependency-scan:
    name: Dependency Vulnerability Scan
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    # Use GitHub's built-in dependency review
    - name: GitHub Dependency Review
      uses: actions/dependency-review-action@v4
      with:
        # Block PRs with high or critical vulnerabilities
        fail-on-severity: high
    
    # NPM audit for additional checks
    - name: NPM Audit
      run: |
        npm audit --audit-level=high
        npm audit --json > npm-audit-report.json
    
    # Upload audit results as artifact
    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: npm-audit-report
        path: npm-audit-report.json
        retention-days: 5

  # Optional: Slack Notification
  notify:
    name: Slack Notification
    needs: [analyze, dependency-scan]
    if: failure()
    runs-on: ubuntu-latest
    
    steps:
    - name: Send Slack Notification
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        text: Security scan detected issues in the repository
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
